Namespace(arch='resnet50', batch_size=16, bottleneck_dim=256, byte_size=256, data='Both', epochs=1, iters_per_epoch=93, label=3, log='Test/Change_lambda/S2T/MKMMD/5/', loss_function='MKMMD', lr=0.003, lr_decay=0.75, lr_gamma=0.0003, momentum=0.9, no_pool=False, non_linear=False, per_class_eval=True, phase='test', print_freq=100, random_frequencies=5, scale_parameter=1, scenario='S2T', scratch=False, seed=None, test_statistic='none', trade_off=5.0, wd=0.0005, workers=2)
Concate data
num_classes: 3
=> using model 'resnet50'
Traceback (most recent call last):
  File "custom_dan.py", line 841, in <module>
    main(args)
  File "custom_dan.py", line 500, in main
    logger.get_checkpoint_path('best'), map_location='cpu')
  File "/home/bkcs/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/bkcs/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/bkcs/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Test/Change_lambda/S2T/MKMMD/5/checkpoints/best.pth'
